name: agrisense
description: "A new Flutter project for Farmers."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.3
  persistent_bottom_nav_bar: ^5.0.2
  mobile_scanner: ^5.1.0
  scan: ^1.6.0
  qr_flutter: ^4.1.0
  country_picker: ^2.0.26
  cached_network_image: ^3.3.1
  pinput: ^4.0.0
  android_sms_retriever: ^1.3.3
  uuid: ^4.4.0
  image_picker: ^1.1.1
  connectivity_plus: ^6.0.3
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.2.8
  location: ^6.0.2
  weather: ^3.1.1
  solar_calculator: ^1.0.3
  osm_nominatim: ^3.0.0
  dio: ^5.5.0
  sentry_flutter: ^8.3.0
  image: ^4.2.0
  file_picker: ^8.0.5
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  draggable_fab: ^0.1.4
  flutter_expandable_fab: ^2.1.0
  google_generative_ai: ^0.4.3
  http: ^1.2.1
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  language_detector: ^1.0.0
  flutter_markdown: ^0.7.2
  ml_kit_ocr: ^0.0.3+1
  read_pdf_text: ^0.2.1
  pdf: ^3.6.5
  webview_flutter: ^4.8.0
  #  sqflite: ^2.3.3+1
  provider: ^6.1.2
  lottie: ^3.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/weather/
    - assets/images/weather/map_pin.svg
    - .env

  fonts:
    - family: K2D
      fonts:
        - asset: fonts/K2D-Bold.ttf
        - asset: fonts/K2D-BoldItalic.ttf
        - asset: fonts/K2D-ExtraBold.ttf
        - asset: fonts/K2D-ExtraBoldItalic.ttf
        - asset: fonts/K2D-ExtraLight.ttf
        - asset: fonts/K2D-ExtraLightItalic.ttf
        - asset: fonts/K2D-Light.ttf
        - asset: fonts/K2D-Italic.ttf
        - asset: fonts/K2D-LightItalic.ttf
        - asset: fonts/K2D-Medium.ttf
        - asset: fonts/K2D-MediumItalic.ttf
        - asset: fonts/K2D-Regular.ttf
        - asset: fonts/K2D-SemiBold.ttf
        - asset: fonts/K2D-SemiBoldItalic.ttf
        - asset: fonts/K2D-Thin.ttf
        - asset: fonts/K2D-ThinItalic.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true